import Head from "next/head";
import Image from "next/image";

import { PostList } from "../components/PostList";

export default function Home({ getPosts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostList getPosts={getPosts} />
    </div>
  );
}

export const getStaticProps = async () => {
  const getResult = await fetch(
    "https://jsonplaceholder.typicode.com/posts?_limit=5"
  );

  const getPosts = await getResult.json();

  return {
    props: {
      getPosts,
    },
  };
};
